### ISSUE TITLE
Truncated and Terminated seem to be inverted

### ISSUE THREAD

**Issue by theovincent** [dfki-ric-underactuated-lab/double_pendulum#5]
Here, 'truncated' is always set to 'False', however you seem to truncate the episode when the number of step count has reached a limit:
https://github.com/dfki-ric-underactuated-lab/double_pendulum/blob/ac80d646ed1f72c4d59670e1a9967ef2a480afcb/src/python/double_pendulum/simulation/gym_env.py#L36-L39

**Comment by fwiebe** [comment]
Yes, you are right. Thanks for pointing it out! Fixed in 3db4524bd4c00b5bc5f2192c4a909b42346b042c
